### ISSUE TITLE
[Bug]: Scanning a LN invoice QR fails without error

### ISSUE THREAD

**Issue by BitcoinErrorLog** [synonymdev/bitkit-react-native#756]
### Describe the bug

If I use the camera scanner to scan a LN QR invoice, it immediately scans then goes back to the previous screen with no effect.

### Reproduce

1. Go to camera scanner from anywhere
2. Scan a LN QR
3. No effect after scanning, no ability to pay LN invoice
4. No error message is given

### Operating system

iOS

### Bitkit version

(23)

**Comment by aldertnl** [comment]
Just tested this as well for a LN QR, cannot confirm this bug, scanner works on my side (23) (iPhone).

**Comment by BitcoinErrorLog** [comment]
It could be the type of invoice being scanned. I tried paying at lnmarkets.com as a deposit -- try both the 0-amount invoice, and try generating a specific one.

**Comment by aldertnl** [comment]
Maybe there is something up with LNmarkets. <img width="584" alt="image" src="https://user-images.githubusercontent.com/81586998/205946832-0d924bd3-ce9a-4d95-bdb5-9d5731254f9e.png">

LNmarkets also failed to generate a specific invoice.

**Comment by aldertnl** [comment]
Just tried again as the issues on LNmarkets side seem to be resolved. I am getting this error when scanning 0-amount invoice on LNmarkets. Bitkit does seem to be able to parse a specified invoice though (on LNmarkets). @coreyphillips @Jasonvdb @BitcoinErrorLog 

![E64C96B5-F206-422D-A59B-4F5283B010BD_4_5005_c](https://user-images.githubusercontent.com/81586998/205983894-c20543bc-eab5-4d2c-9898-7c78c3cd2458.jpeg)

**Comment by coreyphillips** [comment]
When attempting to deposit to LNMarkets without specifying an amount, LNMarkets presents an lnurl-pay string via the qrcode. Unfortunately, Bitkit does not yet support lnurl at this time.

To successfully deposit to LNMarkets in the meantime, an amount must be specified in the textbox below the qrcode. Simply enter the desired amount of satoshis you wish to deposit and click "Request Invoice". This should generate an invoice that Bitkit can recognize.

**Comment by BitcoinErrorLog** [comment]
I suppose then that the bug/feature here is to show appropriate error-handling/notification, and/or to add support for lnurl-pay.

**Comment by coreyphillips** [comment]
This issue has been addressed [here](https://github.com/synonymdev/bitkit/pull/801) and will be included in the next release.

**Comment by JeanlChristophe** [comment]
@coreyphillips can I close the issue?

**Comment by coreyphillips** [comment]
> @coreyphillips can I close the issue?

Please keep it open for now. A scanned lightning invoice containing capital letters followed by a colon (Ex: LIGHTNING:) will currently fail. I'll close this issue once that fix is in.

**Comment by BitcoinErrorLog** [comment]
I still can't read and pay WoS (zero-amount) QR codes with Bitkit.

**Comment by Jasonvdb** [comment]
Working for the incoming build 39. If you select lightning invoice in WOS.

https://user-images.githubusercontent.com/5300488/232447162-03f42269-d1b3-4b01-b743-4b444dcbc5c6.MP4

**Comment by BitcoinErrorLog** [comment]
ohhhh i think i see the issue, it defaults to Lightning Address... lame. I'm still not sure whether we should add support for that...

**Comment by Jasonvdb** [comment]
Right, yeah then I think every user is going to make that mistake if WOS is always going to default to lightning address

**Comment by BitcoinErrorLog** [comment]
I never tried talking to them before, let's see... https://twitter.com/BitcoinErrorLog/status/1647901756137914368

**Comment by JeanlChristophe** [comment]
I am closing this issue, we don't support LN address.
